version: '3.5'
services:
  django:
    build: ./django
    container_name: django
    expose:
      - '8001'
    volumes:
      - ./django/src:/code
    command: uwsgi --socket :8001 --module app.wsgi --py-autoreload 1
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - ./db/dbdata:/var/lib/postgresql/data
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=hogehoge
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testDB