version: '3.9'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl/:/etc/ssl/private
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./backend/src/static:/static
    ports:
      - '80:80'
    depends_on:
      - django
  django:
    platform: linux/amd64
    build: ./backend
    container_name: django
    volumes:
      - ./backend/src:/src
      - ./data/web:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             uwsgi --socket :8000 --workers 4 --master --enable-threads --module app.wsgi"
    depends_on:
      - db
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=testDB
      - DB_USER=hogehoge
      - DB_PASS=password
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    sysctls:
      net.core.somaxconn: 65536
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - ./db/dbdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=hogehoge
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testDB
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    command: postgres -c stats_temp_directory=/tmp